<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\ProductController;
use App\Http\Controllers\Api\OrderController;
use App\Http\Controllers\Api\UserActivityController; // Bonus

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "api" middleware group. Make something great!
|
*/

// --- Guest Routes ---
Route::post('/register', [AuthController::class, 'register'])->name('api.register');
Route::post('/login', [AuthController::class, 'login'])->name('api.login');

// --- Email Verification Routes ---
// This route will be generated by Laravel's verification email link.
// It needs to be publicly accessible but requires a signed URL.
Route::get('/email/verify/{id}/{hash}', [AuthController::class, 'verifyEmail'])
    ->middleware(['signed', 'throttle:6,1']) // 'signed' middleware validates the signature
    ->name('verification.verify'); // Name must match Laravel's default for link generation

// Route for authenticated users to request a new verification email.
Route::post('/email/verification-notification', [AuthController::class, 'resendVerificationEmail'])
    ->middleware(['auth:sanctum', 'throttle:6,1']) // User must be authenticated (but not yet verified)
    ->name('verification.send');

// --- Authenticated Routes ---
Route::middleware('auth:sanctum')->group(function () {
    // Auth
    Route::post('/logout', [AuthController::class, 'logout'])->name('api.logout');
    Route::get('/user', [AuthController::class, 'user'])->name('api.user');

    // Products
    Route::get('/products', [ProductController::class, 'index'])->name('api.products.index');
    Route::get('/products/{product:slug}', [ProductController::class, 'show'])->name('api.products.show'); // Product by slug

    // Orders
    Route::post('/orders', [OrderController::class, 'store'])->name('api.orders.store');
    Route::get('/orders', [OrderController::class, 'index'])->name('api.orders.index');
    Route::get('/orders/{order}', [OrderController::class, 'show'])->name('api.orders.show'); // Specific order

    // User Activity Log (Bonus)
    Route::get('/user/activity-logs', [UserActivityController::class, 'index'])->name('api.user.activity');
    // Example admin route for all logs (would need admin authorization)
    // Route::get('/admin/activity-logs', [UserActivityController::class, 'allLogs'])->name('api.admin.activity');
});
