<template>
    <button
        class="
        w-full
        border-[1px] 
        hover:bg-white 
        border-[#80041c] 
        p-3
        text-[22px] 
        font-roboto 
        hover:text-[#80041c] 
        bg-[#80041c] 
        text-white 
        hover:underline 
        hover:font-bold 
        cursor-pointer"
    >
        <slot />
    </button>
</template>
